#!/bin/csh
#SBATCH --job-name=mix_75_high_field_0500uT_settle
#SBATCH --nodes=1
#SBATCH --ntasks=120
#SBATCH --oversubscribe
#SBATCH --time 36:00:00
#SBATCH --mail-user sikka@umd.edu
#SBATCH --mail-type=ALL

#############################################################
# change the below input variable to your own filename
#############################################################


set dir=/scratch/zt1/project/hartzell-lab/user/sikka/SIMS-LIGGGHTS/psyche_sims/mixture/75_high/field_0500uT
set codeexe=/scratch/zt1/project/hartzell-lab/user/sikka/SIMS-LIGGGHTS/avalanching_experiments/lmp_auto

cd $dir
module load openmpi
module load eigen
module load boost
mpirun -np 120 $codeexe -echo both -i ./in.settle > ./output_settle.txt